name: Travelon
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  wifi_scan: ^0.4.1+2
  path_provider: ^2.1.5
  csv: ^6.0.0
  http: ^1.5.0
  flutter_osm_plugin:
  permission_handler:
  flutter_map:
  latlong2:
  flutter_bloc:
  bloc: 
  flutter_native_splash: ^2.4.6
  lottie:
  smooth_page_indicator:
  flutter_svg:
  go_router:
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  dio: ^5.9.0
  flutter_dotenv:
  another_flushbar: ^1.12.32
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  intl: ^0.20.2
  socket_io_client: ^3.1.4
  audioplayers: ^6.5.1
  vibration: ^3.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/sounds/sos_help.mp3
     - assets/sounds/geo_warning.mp3
     - assets/splashlogo/
     - assets/fonts/
     - assets/images/lottieanimations/
     - assets/images/svgfiles/
     - .env
  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Regular.ttf
        - asset: assets/fonts/ArchivoBlack-Regular.ttf
          weight: 700
    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf
          

#for the native splash
flutter_native_splash:
  color: "#ffffff"
  image: assets/splashlogo/travelon-splash-logo.png
  android_12:
    image: assets/splashlogo/travelon-splash-logo.png
    icon_background_color: "#ffffff"

